// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgiOri5hV0jptfFEtssbuwvc5bJmhrgZs',
    appId: '1:355375508768:web:a278b73f8ab5cc74a93b45',
    messagingSenderId: '355375508768',
    projectId: 'blablacar-f21cc',
    authDomain: 'blablacar-f21cc.firebaseapp.com',
    storageBucket: 'blablacar-f21cc.firebasestorage.app',
    measurementId: 'G-XLN0RX4J5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEf4hIe1hooPHqL-HOnCuuRk24_ms9tmg',
    appId: '1:355375508768:android:4507445a16513e7fa93b45',
    messagingSenderId: '355375508768',
    projectId: 'blablacar-f21cc',
    storageBucket: 'blablacar-f21cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmKvh16dO2MFVWxv-t1MVfm9fpgpAEDk8',
    appId: '1:355375508768:ios:8a4cff652d8ab5dfa93b45',
    messagingSenderId: '355375508768',
    projectId: 'blablacar-f21cc',
    storageBucket: 'blablacar-f21cc.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmKvh16dO2MFVWxv-t1MVfm9fpgpAEDk8',
    appId: '1:355375508768:ios:8a4cff652d8ab5dfa93b45',
    messagingSenderId: '355375508768',
    projectId: 'blablacar-f21cc',
    storageBucket: 'blablacar-f21cc.firebasestorage.app',
    iosBundleId: 'com.example.week3BlablaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgiOri5hV0jptfFEtssbuwvc5bJmhrgZs',
    appId: '1:355375508768:web:83920c62c0b83fc4a93b45',
    messagingSenderId: '355375508768',
    projectId: 'blablacar-f21cc',
    authDomain: 'blablacar-f21cc.firebaseapp.com',
    storageBucket: 'blablacar-f21cc.firebasestorage.app',
    measurementId: 'G-ERBKFTQ7GL',
  );
}
